### ISSUE TITLE
A terminal flatpak command is not working.

### ISSUE THREAD

**Issue by NotPiKei** [GNOME-Web-Extensions/Get-Started#8]
When I use this command:
`flatpak run --command='sh' org.gnome.Epiphany`

I get this output:
`error: app/org.gnome.Epiphany/x86_64/master not installed`

**Comment by CleoMenezesJr** [comment]
Are you sure you have this installed version? It may have the Nightly, Canary or Beta version.

**Comment by NotPiKei** [comment]
> Are you sure you have this installed version? It may have the Nightly, Canary or Beta version.

I tried all the epiphany versions, none of them worked with this. Don't worry thought, I will close this issue.
